jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 180
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack-lts-14:
        BUILD: stack
        ARGS: "--resolver lts-14"
    maxParallel: 3
  steps:
  - bash: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/
      stack setup $ARGS > /dev/null
      stack --install-ghc $ARGS build --only-dependencies
      stack $ARGS test --bench --no-run-benchmarks --no-run-tests
      stack $ARGS test --bench --no-run-benchmarks --jobs 1 # non-parallel test execution
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Installation ${{parameters.os}} & Test'
